config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  # devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: {
  registrations: 'users/registrations',
  sessions: 'users/sessions',
  passwords: 'users/passwords',
  confirmations: 'users/confirmations',
  unlocks: 'users/unlocks',
}


  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # get "/google_books/search", to: "google_books#search"

  resources :clubs, only: [:index, :new, :create, :show] do
    post "add_user", on: :member
    delete "remove_user", on: :member
  end
  resources :books, param: :google_id, only: [:index, :show] do
    resources :reviews, only: [:create, :destroy]
  end

  resources :meetings, only: [:index,:new, :create, :show]


  resources :lists do
    post 'add_book', on: :member
  end
  post '/lists/add_book', to: 'lists#add_book', as: 'add_book_to_list'


  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  belongs_to :book
  belongs_to :club
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController

  def index
      @meetings = Meeting.order(date: :desc)
  end
  def show
    @meeting = Meeting.find(params[:id])
  end

  def new
    @meeting = Meeting.new
  end

  def create
    @meeting = Meeting.new(meeting_params)
    if @meeting.save
      redirect_to @meeting, notice: 'Meeting was successfully created.'
    else
      render :new
    end
  end


  private

  def set_meeting
    @meeting = Meeting.find(params[:id])
  end

  def meeting_params
    params.require(:meeting).permit(:book_id, :club_id, :location, :date, :status)
  end

end

app/views/meetings/index.html.erb
<div class="meetings-container">
  <h2 class="page-title">Meetings</h2>

<div class="meetings-list">
  <% @meetings.each do |meeting| %>
    <div class="meeting-card">
      <div class="meeting-info">
        <p class="book-title"><%= meeting.book.title.upcase %></p>
        <p class="date"><%= meeting.date.strftime("%d/%m/%y") %></p>
      <!-- Show button to go to the meeting's show page -->
      <%= link_to 'More', meeting_path(meeting), class: 'btn btn-tertiary' %>
      </div>


      <!-- White circle on the right -->
      <div class="circle">
        <img src="<%= meeting.book.cover_url %>" >
      </div>

    </div>
  <% end %>
</div>

<div class = "buttons">
  <%= link_to 'New Meeting', new_meeting_path, class: 'btn btn-new' %>


</div>
</div>

app/views/meetings/new.html.erb
 <div class="container p-5 mt-5">
  <div  class="row justify-content-center">
    <div  class="col-12 col-lg-6">


<%= form_with model: @meeting, local: true do |form| %>
  <% if @meeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>
      <ul>
        <% @meeting.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :book_id %>
    <%= form.select :book_id, Book.all.collect { |book| [book.title, book.id] }, prompt: "Select Book" %>
  </div>

  <div class="field">
    <%= form.label :club_id %>
    <%= form.select :club_id, Club.all.collect { |club| [club.name, club.id] }, prompt: "Select Club" %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_local_field :date %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="actions">
    <%= form.submit   %>
  </div>
<% end %>

</div>
</div>
</div>

app/views/meetings/show.html.erb
<!-- Club Meeting SHOW Page -->

<div class="show-container">
  <div class="cover-circle"><img src="<%= @meeting.book.cover_url %>" ></div>
  <h2 class="page-title"><%= @meeting.book.title %></h2>

  <div class="meeting-show-card">

<h1>Club Meeting Details</h1>

<p><strong>Book:</strong> <%= @meeting.book.title %></p>
<p><strong>Club:</strong> <%= @meeting.club.name %></p>
<p><strong>Location:</strong> <%= @meeting.location %></p>
<p><strong>Date:</strong> <%= @meeting.date.strftime("%B %d, %Y at %I:%M %p") %></p>
<p><strong>Status:</strong> <%= @meeting.status %></p>

<div class="buttons">
<%= link_to 'Back to Meetings', meetings_path , class: "btn btn-primary"%>
</div>

  </div>
  <div class="notes-section">
    <h3>Notes</h3>
    <p>.......................................................</p>
    <p>.......................................................</p>
    <p>.......................................................</p>
    <p>.......................................................</p>
  </div>
</div>