config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  # devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: {
  registrations: 'users/registrations',
  sessions: 'users/sessions',
  passwords: 'users/passwords',
  confirmations: 'users/confirmations',
  unlocks: 'users/unlocks',
}


  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # get "/google_books/search", to: "google_books#search"

  resources :clubs, only: [:index, :new, :create, :show] do
    post "add_user", on: :member
    delete "remove_user", on: :member
  end
  resources :books, param: :google_id, only: [:index, :show] do
    resources :reviews, only: [:create, :destroy]
  end

  resources :meetings, only: [:index,:new, :create, :show]


  resources :lists do
    post 'add_book', on: :member
  end
  post '/lists/add_book', to: 'lists#add_book', as: 'add_book_to_list'


  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="<%= root_path %>">
     <%# <img src="https://res.cloudinary.com/do1nrl43q/image/upload/v1738456047/Logo_c_reo7ar.png" /> %>
    </a>

    <div class="bookshelf">
<div class="book-s"></div>
<div class="book-l ro"></div>
<div class="book-m"></div>
<div class = "gap"></div>
<div class="book-s"></div>
<div class="book-m"></div>
<div class="book-m ro"></div>
<div class="book-l"></div>
<div class = "gap"></div>
<div class="book-m"></div>
<div class="book-s"></div>
<div class = "gap"></div>
<div class="book-l"></div>
<div class="book-m"></div>
    </div>


    <button class="books-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
       <div class="ro90"></div>
       <div class="ro90"></div>
       <div class="ro90"></div>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">
      <% if user_signed_in? %>
        <ul class="navbar-nav ms-auto">
<%#
          <%# <%= link_to profile_path, class: "nav-link" do %>
              <%# Dashboard %>
          <%# <% end %>

          <li class="nav-item">
            <%= link_to "Library", books_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "My Meetings", meetings_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "My Lists", lists_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Manage Account", edit_user_registration_path, class: "nav-link" %>
          </li>
          <%# <li class="nav-item">
            <%# <%= link_to "Change Password", edit_user_password_path, class: "nav-link" %>
          <%# </li>  %>
          <li class="nav-item">
             <%= link_to destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link" do %>
             Sign Out
            <%# <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
              <% end %>
          </li>
        </ul>
      <% else %>
        <ul class="navbar-nav ms-auto">
               <li class="nav-item">
            <%= link_to "Library", books_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
          </li>
        </ul>
      <% end %>




    </div>
  </div>
</nav>