config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  # devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: {
  registrations: 'users/registrations',
  sessions: 'users/sessions',
  passwords: 'users/passwords',
  confirmations: 'users/confirmations',
  unlocks: 'users/unlocks',
}


  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # get "/google_books/search", to: "google_books#search"

  resources :clubs, only: [:index, :new, :create, :show] do
    post "add_user", on: :member
    delete "remove_user", on: :member
  end
  resources :books, param: :google_id, only: [:index, :show] do
    resources :reviews, only: [:create, :destroy]
  end

  resources :meetings, only: [:index,:new, :create, :show]


  resources :lists do
    post 'add_book', on: :member
  end
  post '/lists/add_book', to: 'lists#add_book', as: 'add_book_to_list'


  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :list_books, dependent: :destroy
  has_many :lists, through: :list_books
  has_many :reviews, dependent: :destroy
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

def index
  if params[:query].present?
    @books = GoogleBooksService.search_books(params[:query])
  else
    # @top_rated_books = @books.order(average_rating: :desc).limit(7) # Fetch top 7 rated books

    @books = [] # No books are loaded until a search is performed
  end
end


  def show
    if params[:google_id].present?
      @book = GoogleBooksService.find_book(params[:google_id])
      @lists = current_user.lists
    else
      redirect_to books_path, alert: "Book not found."
    end
  end





  # GET /books/new
# def new
# @book = Book.new
# end

# def create
#   @book = Book.new(book_params)
#   if @book.save
#     redirect_to books_path, notice: "Book was successfully created."
#   else
#     render :new, status: :unprocessable_entity
#   end
# end

    # GET /books/1



# private
#   def book_params
#     params.require(:book).permit(:title, :cover_url, :overview)
#   end

end

app/views/books/index.html.erb
<div class ="books-page">

<div  class="row justify-content-center">
  <div class="col-12 col-lg-6">

<h1 class="page-title">Library</h1>

<div class="books-index">

<h2>Search for Books</h2>

<%= form_with url: books_path, method: :get, local: true do %>
  <input type="text" name="query" placeholder="Enter book title..." value="<%= params[:query] %>">
  <button class="btn btn-tertiary" type="submit">Search</button>
<% end %>


<% if @books.any? %>
  <h3 style="  display: flex; align-items: center; justify-content: center; padding:10%;">Search Results:</h3>
  <div class="books-container">
    <% @books.each do |book| %>
      <div class="book-card">
        <div class="book-cover">
          <% if book[:cover_url] %>
            <img src="<%= book[:cover_url] %>" alt="<%= book[:title] %> cover" class="book-image">
          <% else %>
            <div class="book-image-placeholder"></div>
          <% end %>
        </div>
        <div class="book-info">
          <h4><%= book[:title] %></h4>
          <p><strong>Author:</strong> <%= book[:authors] %></p>
                    <p>Published: <%= book[:publication_year] %></p>
           <% if book[:average_rating].present? && book[:average_rating] != "No rating"  %>
           <p> <strong>Rating:</strong> <%= book[:average_rating] %> / 5</p>
           <% end %>
          <%= link_to "View Details", book_path(book[:google_id]), class: "view-details" %>
        </div>
      </div>
    <% end %>
  </div>
<% else %>
  <p>No books yet. Try searching above!</p>
  <div class="stacked-container">
        <div class="stacked-item item5"></div>
        <div class="stacked-item item4"></div>
        <div class="stacked-item item3"></div>
        <div class="stacked-item item2"></div>
        <div class="stacked-item item1"></div>

    </div>
<% end %>

</div>
</div>
</div>
</div>

app/views/books/new.html.erb
 <div class="container p-5 mt-5">
  <div  class="row justify-content-center">
    <div  class="col-12 col-lg-6">

 <h3>Create a new book entry</h3>
        <%= simple_form_for @book do |f| %>
          <%= f.input :title, placeholder: 'Enter a title' %>
          <%# <%= f.input :cover_url, as: :file %>
          <%= f.submit class: 'btn btn-flat' %>
        <% end %>
</div>
</div>
</div>

app/views/books/show.html.erb
<div class ="show-container" id = "book-page">

<div class="buttons mt-1">
  <%= link_to "Back to Search", books_path, class: "btn btn-secondary" %>

  <% if @lists.any? %>
    <%= form_tag add_book_to_list_path, method: :post, local: true do %>
      <div class="form-group mb-2">
        <%= label_tag :list_id, "Select a List" %>
        <%= select_tag :list_id, options_from_collection_for_select(@lists, :id, :name), class: "form-control" %>
      </div>

      <%= hidden_field_tag "book[google_id]", @book[:id] %>
      <%= hidden_field_tag "book[title]", @book[:title] %>
      <%= hidden_field_tag "book[cover_url]", @book[:cover_url] %>
      <%= hidden_field_tag "book[overview]", @book[:overview] || "No description available." %>

      <%= submit_tag "Add Book to List", class: "btn btn-primary" %>
    <% end %>
  <% else %>
    <p>You don't have any lists yet. <%= link_to "Create one", new_list_path %></p>
  <% end %>
</div>





<div class= "line"></div>

<div class="container mt-4">
   <div  class="row justify-content-center">
     <div class="col-12 col-lg-6">


<div class="book-details">
<h2><%= @book[:title] %></h2>
  <div class="book-cover mt-4">
<% if @book[:cover_url] %>
  <img src="<%= @book[:cover_url] %>" alt="<%= @book[:title] %>" width="200">
<% end %>
</div>

 <div class="book-metadata">
<p><strong>Author:</strong> <%= @book[:authors] %></p>
<p><strong>Published:</strong> <%= @book[:publication_year] %></p>
<p><strong>Pages:</strong> <%= @book[:page_count] %></p>
<p><strong>Categories:</strong> <%= @book[:categories].split("/ ").take(5).join(", ") %></p>
<p><strong>Rating:</strong> <%= @book[:average_rating] %> / 5</p>
</div>

<div class= "line"></div>

  <div class="notes-section" id = "book-overview">
    <div>
      <%= raw @book[:overview] %>
    </div>
  </div>
</div>

<div class = "container mt-4">
  <h2>Reviews</h2>
</div>

</div>
</div>
</div>

</div>